@extends('client.layouts.master')
@section('title', 'Tourm - Dịch vụ lưu trú và du lịch')
@section('content')
    @include('client.home.components.hero')
    @include('client.home.components.booking')
    @include('client.home.components.category')
    @include('client.home.components.destination')
    @include('client.home.components.about')
    @include('client.home.components.services')
    @include('client.home.components.gallery')
    @include('client.home.components.counter')
    @include('client.home.components.brand')
    @include('client.home.components.blog')
@endsection
